### ISSUE TITLE
More than 1 grouping factors

### ISSUE THREAD

**Issue by marivascruz** [mvuorre/brmstools#1]
Hi Matti, 

Thanks for the package. I noticed you do not support visualizations with multiple grouping factors.
The phylogenetic meta-analysis model comes to mind: https://cran.r-project.org/web/packages/brms/vignettes/brms_phylogenetics.html

Manuel

**Comment by mvuorre** [comment]
Thanks for the comment. I'll get around to implementing this soon: The most straightforward way to do this would be to allow the user to choose which grouping factor to use, if there are many in the model.

**Comment by marivascruz** [comment]
Thank you, Matti. The straightforward suggestion is a good one.

**Comment by mvuorre** [comment]
This is now implemented with the (optional) `grouping` argument that can be passed to all functions. It defaults to `grouping = NA` which picks the first / only grouping factor.
