### ISSUE TITLE
Ordinal multi-level effects plots using 'forest'  or another function?

### ISSUE THREAD

**Issue by dan-chapman** [mvuorre/brmstools#3]
Hi Matti, love the package, really useful for plotting quickly. I'm wondering if you plan to offer support for plotting the random effects from multi-level ordinal models computed using brms? The following error pops up when I attempt to implement directly: 
```
Error in coef(model, summary = FALSE)[[grouping]][, , parameter] : 
  subscript out of bounds
```
I'm assuming by the error that this is due to the nature of how the ordinal effects are stored in brms? (Running R 3.5.0 in RStudio and just reinstalled the dev version of brmstools today)

**Comment by mvuorre** [comment]
Hi, thanks for the feedback. I don't have time to implement this feature in the near future. I think it would be quite straightforward, however, to do it yourself. And of course I am open to a pull request on this feature.

Also, that figure shouldn't be very difficult to draw 'manually' using brms' native functions and [ggplot2](https://github.com/tidyverse/ggplot2), for example.

**Comment by dan-chapman** [comment]
Thanks Matti. Those were my thoughts as well, mainly just curious if you had any intentions of modifying the function. Thanks!
