### ISSUE TITLE
Error in FUN(X[[i]], ...) : object '2.5%ile' not found

### ISSUE THREAD

**Issue by LaurentSmeets** [mvuorre/brmstools#4]
I am trying the following code, but getting a weird error message, what I am doing wrong?
I am getting this error message: Error in FUN(X[[i]], ...) : object '2.5%ile' not found

```R
simpelmodel1<-brm(popular~1 + extrav+(1+extrav|class), data=popular2data, warmup = 1000, iter =5000, chains = 2, inits= "random", control = list(adapt_delta = 0.96),save_all_pars = TRUE, cores= 2) 

spaghetti(simpelmodel1, xvar = "extrav")
```
This is thus a super simple model for demonstration purposes. 
The forest function does work.

**Comment by mvuorre** [comment]
Hi, this is now fixed in the latest version. Please reinstall brmstools and try again.

**Comment by LaurentSmeets** [comment]
Thanks for the quick reply and fix.
