### ISSUE TITLE
Scale transformation in forest plot

### ISSUE THREAD

**Issue by StaffanBetner** [mvuorre/brmstools#7]
It would be useful to be able to transform the parameters draws before plotting, e.g. if one have estimated a simple logistic model with a random intercept (with no other terms), it would be useful to get estimates on the probability scale. (inverse logit)

**Comment by mvuorre** [comment]
Hi, for custom plots, I strongly recommend checking out the R packages **tidybayes** and **ggridges**. You'll be able to draw any kind of forest plot with those packages with little coding.

<https://mjskay.github.io/tidybayes/index.html>

<https://github.com/clauswilke/ggridges>
