### ISSUE TITLE
Forest plot for nested random effects

### ISSUE THREAD

**Issue by StaffanBetner** [mvuorre/brmstools#8]
Let say I have a regression model like this: Y ~ (1|A/B), then I can't specify the interaction (A:B) in the grouping argument of the forest function without error 

> Error: object 'A' not found

with the call: 

> forest(model, grouping = "A:B")

**Comment by mvuorre** [comment]
Yes the function probably does not support models with more than two levels. I recommend checking out the tidybayes package which will easily get the parameters you want.
